#macro VIEW_W 320
#macro VIEW_H 180
#macro PLAYER_COLLISION_MASK_SPRITE spr_player_collision_mask

#macro PLAYER_LAYER_NAME "player"
#macro PLAYER_START_GAME_WITHOUT_SAVE_XPOS 200
#macro PLAYER_START_GAME_WITHOUT_SAVE_YPOS 872
#macro NEXUS_START_X_POSITION 200
#macro NEXUS_START_Y_POSITION 872

// water
#macro WATERDIVISION 3